project:
  type: book
  output-dir: _book

book:
  title: "Epigenetics Workshop"
  author: 
  - name: Adele Barugahare 
    affiliations:
      - id: mgbp
        name: Monash Genomics & Bioinformatics Platform
      - id: tlab
        name: Turner Laboratory
  - name: Daniel Thiele
    affiliations:
      - id: lglab
        name: La Gruta Lab
  - name: David Chisanga
    affiliations:
      - id: slab
        name: Shi Lab
  - name: Pushkar Dackle
    affiliations:
      - ref: tlab
  - name: Giulia Iacono
    affiliations:
      - ref: mgbp
  date: "03/20/2026"
  chapters:
    - index.qmd
    - 00_introduction.qmd
    - part: "ATACseq Tutorial"
      chapters:
        - 01_atacseq_introduction.qmd
        - 02_atacseq_processing.qmd
        - 03_atacseq_qc.qmd
        - 04_atacseq_peak_calling.qmd
        - 05_atacseq_differential_accessibility.qmd
        - 06_atacseq_downstream_analysis.qmd
    - part: "Cut&Tag Tutorial"
      chapters:
        - 07_cuttag_introduction.qmd
        - 08_cuttag_processing.qmd
        - 09_cuttag_qc.qmd
        - 10_cuttag_peak_calling.qmd
        - 11_cuttag_differential_accessibilty.qmd
        - 12_cuttag_downstream_analysis.qmd
bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand

editor: visual

execute:
  freeze: auto

